activity_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [    
    url(r'^subjects/', include('subjects.urls', namespace='subjects')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home),
]

urlpatterns += staticfiles_urlpatterns()

subjects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.subject_list, name='list'),
    url(r'(?P<subject_pk>\d+)/(?P<activity_pk>\d+)/$', views.activity_detail, name='activity'),
    url(r'(?P<pk>\d+)/$', views.subject_detail, name='detail'),
]

subjects/models.py
from __future__ import unicode_literals

from django.db import models
from django.forms import ModelForm

# Create your models here.
class Subject(models.Model):
    title = models.CharField(max_length=255)
    color = models.CharField(max_length=6)
    priority = models.IntegerField(default=0)
    
    class Meta:
        ordering = ['priority',]
    
    def __str__(self):
        return self.title

class Activity(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    link = models.CharField(max_length=255)
    subject = models.ForeignKey(Subject)
    
    class Meta:
        ordering = ['order',]
        
    def __str__(self):
        return self.title
        
class Log(models.Model):
    duration = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True, default='')
    activity = models.ForeignKey(Activity)
    
    class Meta:
        ordering = ['-created_at',]
        
    def __str__(self):
        return self.comment
   
    

subjects/forms.py
from django import forms
import math
from .models import Subject, Activity, Log
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.utils.translation import ugettext_lazy as _


class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['title', 'color', 'priority']
        
    def clean_priority(self):
        priority = self.cleaned_data.get('priority')
        if priority < 1:
            raise forms.ValidationError("Priority must be a positive number")
        return math.fabs(priority) 
        
# http://stackoverflow.com/questions/16356289/how-to-show-datepicker-calender-on-datefield   
# https://www.reddit.com/r/django/comments/2abs90/how_can_i_use_a_datepicker_in_a_crispy_form/
# class LogForm(forms.Form):
#     start_time = forms.CharField(widget=forms.TextInput(attrs={'class': 'datepicker'}))
#     duration = forms.TextInput(
#     comment = forms.CharField(widget=forms.TextInput(attrs={'size': '40'}))
    
    
class LogForm(forms.ModelForm):
#     duration = forms.IntegerField(required=True)
    
    class Meta:
        model = Log
        fields = ('duration', 'comment')
#         labels = {
#             'duration': _('Duration (Minutes)')
#         }
#         widgets = {
#             'start_time': forms.DateInput(attrs={'class':'datepicker'}) 
#         }
        
#     def __init__(self, *args, **kwargs):
#         super(LogForm, self).__init__(*args, **kwargs)
#         self.helper = FormHelper()
#         self.helper.form_method = 'post'
#         self.helper.add_input(Submit('submit', 'Add Log Entry'))
        
       

activity_log/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

subjects/views.py
from django.shortcuts import render, get_object_or_404 
from .models import Subject, Activity, Log
from .forms import LogForm

def subject_list(request):   
    subjects = Subject.objects.all()
    context = {
        'subjects': subjects
    }
    
    return render(request, 'subjects/subject_list.html', context)

def subject_detail(request, pk):
    subject = get_object_or_404(Subject, pk=pk)
    context = {
        'subject': subject
    }
    return render(request,  'subjects/subject_detail.html', context)


def activity_detail(request, subject_pk, activity_pk):
    
    # Get all Log entries for given activity
    def getLogs(activity_pk):
        try:
            logs = Log.objects.filter(activity_id=activity_pk)
            
            # Change display of datetime variables
            for log in logs:
                log.created_at = log.created_at.strftime("%Y-%m-%d %H:%M")
                hours = log.duration // 60
                minutes = log.duration % 60
                log.duration = "%d:%02d" % (hours, minutes)
            
        except Log.DoesNotExist:
            logs = None
            
        return logs
    
    # Get activity from DB, Form object, and Log entries
    activity = get_object_or_404(Activity, subject_id=subject_pk, pk=activity_pk)
    logs = getLogs(activity_pk)
    
    # Validate form
    if request.method == "POST":
        data = request.POST
        hours = int(data['hour'])
        minutes = int(data['min'])
        seconds = int(data['sec'])
        
        if seconds >= 30:
            minutes = minutes + 1
            
        dur = hours * 60 + minutes

        logObj = Log(comment=data['comment'], duration=dur, activity=activity)
        logObj.save()
        logs = getLogs(activity_pk)
        
    context = {
        'activity': activity,
        'logs': logs,
    }
    
    return render(request, 'subjects/activity_detail.html', context)

subjects/templates/subjects/activity_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}{{ activity.title }} - {{ activity.subject.title }}{% endblock %}

{% block css %}
<link type="text/css" media="screen" href="{% static 'css/stopwatch.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="jumbotron">
    <h2>{{ activity.title }} <small>{{ activity.subject.title }}</small></h2>
    <p>{{ activity.description }}</p>
</div>

    <!--<div id="datetimepicker" class="input-append date">-->
    <!--  <input type="text"></input>-->
    <!--  <span class="add-on">-->
    <!--    <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>-->
    <!--  </span>-->
    <!--</div>-->

<div class="row">
    <div class="col-md-3">
        <h2>Add New Entry:</h2>
        <form method="POST">{% csrf_token %}
            <textarea name="comment" rows="3">Enter Comment Here...</textarea>
            <div class="stopwatch">
                
                <b>Duration (H:M:S): </b>
                <input type="number" id="stopwatch_hr" class="stopwatch_number" name="hour" min="0" step="1"/> : 
                <input type="number" id="stopwatch_min" class="stopwatch_number" name="min" min="0" max="59" step="1"/> : 
                <input type="number" id="stopwatch_sec" class="stopwatch_number" name="sec" min="0" max="59" step = "1"/>
                
                <button type="button" id='play_pause' class="btn btn-default btn-md">
                    <span class="glyphicon glyphicon-play"></span> Start
                </button>
                
            </div>
            <br/>
            <input type="submit" class="btn btn-primary" value="Add New Log">
        </form>
    </div>
    
    <div class="col-md-9">
        <h2>Activity Log:</h2>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <td>Created On</td>
                    <td>Duration</td>
                    <td>Comment</td>
                </tr>
            </thead>  
            
            {% for log in logs %}
            <tr>
                <td>{{ log.created_at }}</td>
                <td>{{ log.duration }}</td>
                <td>{{ log.comment }}</td>
            </tr>
            {% endfor %}
        </table>  
    </div>
</div>


{% endblock %}


{% block js-foot %}
<script src="{% static 'js/stopwatch.js' %}"></script>
{% endblock %}
    

subjects/templates/subjects/subject_detail.html
{% extends "base.html" %}

{% block title %}{{ subject.title }}{% endblock %}

{% block content %}
<article>
    <h2>{{ subject.title }}</h2>
    
    <section>
        {% for activity in subject.activity_set.all %}
            <h3>
            <a href="{% url 'subjects:activity' subject_pk=activity.subject.pk activity_pk=activity.pk %}">
                {{ activity.title }}
            </a>
            </h3>
            {{ activity.description }}
        {% endfor %}
    </section>
</article>
{% endblock %}

subjects/templates/subjects/subject_list.html
{% extends "base.html" %}

{% block title %}Subjects{% endblock %}

{% block content %}

<ul class="nav nav-pills nav-stacked">
    {% for subject in subjects %}
    <li role="presentation"><a href="{% url 'subjects:detail' pk=subject.pk %}">{{ subject.title }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Sandbox site for programming in Django, jQuery, JavaScript">
    <meta name="author" content="Theodore Lano">
    <link rel="icon" href="{% static 'img/tl_favicon.png' %}">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/navbar.css' %}" rel="stylesheet">
    
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
    
    {% block css %}{% endblock %}

  </head>

  <body>

    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Ted's Django & Bootstrap Sandbox</a>
          </div>
          
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'views.home' %}">Home</a></li>
              <li><a href="{% url 'subjects:list' %}">Activity Log</a></li>
              <!--<li class="dropdown">-->
              <!--  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
              <!--  <ul class="dropdown-menu">-->
              <!--    <li><a href="#">Action</a></li>-->
              <!--    <li><a href="#">Another action</a></li>-->
              <!--    <li><a href="#">Something else here</a></li>-->
              <!--    <li role="separator" class="divider"></li>-->
              <!--    <li class="dropdown-header">Nav header</li>-->
              <!--    <li><a href="#">Separated link</a></li>-->
              <!--    <li><a href="#">One more separated link</a></li>-->
              <!--  </ul>-->
              <!--</li>-->
            </ul>
            <!--<ul class="nav navbar-nav navbar-right">-->
            <!--  <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>-->
            <!--  <li><a href="../navbar-static-top/">Static top</a></li>-->
            <!--  <li><a href="../navbar-fixed-top/">Fixed top</a></li>-->
            <!--</ul>-->
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

    {% block content %}{% endblock %}

    </div> <!-- /container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block js-foot %} {% endblock js-foot %}
    
  </body>
</html>

templates/countdown.html
<ul id="countdown">
	<li class="num_block">
		<div class="number days">00</div>
		<span class="strikethrough"></span>
		<p class="timeLabel">DAYS</p>
	</li>
	<li class="num_block">
		<div class="number hours">00</div>
		<span class="strikethrough"></span>
		<p class="timeLabel">HOURS</p>
	</li>
	<li class="num_block">
		<div class="number minutes">00</div>
		<span class="strikethrough"></span>
		<p class="timeLabel">MINUTES</p>
	</li>
	<li class="num_block">
		<div class="number seconds">00</div>
		<span class="strikethrough"></span>
		<p class="timeLabel">SECONDS</p>
	</li>
</ul>

<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.0.min.js"></script>
<script src="js/countdown.js"></script>

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}Well hello there!{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/countdown.css' %}">
{% endblock %}
{% block content %}
<div class="jumbotron">
<h1>Hello Ted</h1>
<p>If you're not Ted then I'm not sure how you got here or what you're looking for, but here's a countdown to my birthday.  I built it myself, not bad eh?<p>
  <!--<a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">Don't Click Me &raquo;</a>-->
</p>
</div>


<ul id="countdown">
	<li class="num_block">
		<div class="number days">00</div>
		<span class="strikethrough"></span>
		<p class="timeLabel">DAYS</p>
	</li>
	<li class="num_block">
		<div class="number hours">00</div>
		<span class="strikethrough"></span>
		<p class="timeLabel">HOURS</p>
	</li>
	<li class="num_block">
		<div class="number minutes">00</div>
		<span class="strikethrough"></span>
		<p class="timeLabel">MINUTES</p>
	</li>
	<li class="num_block">
		<div class="number seconds">00</div>
		<span class="strikethrough"></span>
		<p class="timeLabel">SECONDS</p>
	</li>
</ul>

{% endblock %}

{% block js-foot %}
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.0.min.js"></script>
<script src="{% static 'js/countdown.js' %}"></script>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}

<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/layout.css' %}"> 
    </head>  
    <body>
        
        <div class="site-container">
            <nav>
                <a href="{% url 'views.home' %}">Home</a>
                <a href="{% url 'subjects:list' %}">Subjects</a> 
            </nav>
            
            {% block content %}{% endblock %}
        </div>
        
    </body>
</html>